config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'

  get 'my_portfolio', to: "users#my_portfolio"

# handles searching for the infomration entered in the input
  get 'search_stocks', to: 'stocks#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

  def self.new_from_lookup(ticker_symbol)

    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)

    price = strip_commas(looked_up_stock.l)

    new(name: looked_up_stock.name, ticker: looked_up_stock.symbol, last_price: price)

  end

# remove the comments from the number coming in
  def self.strip_commas(number)
    # gsub takes 2 arguments, 1st is what you want to remove, 2nd is what you want to replace it with
    number.gsub(",", "")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

    def search
      # byebug
      @stock = Stock.new_from_lookup(params[:stock])
      render 'users/my_portfolio'
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def my_portfolio

end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>



    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">FinanceTracker</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/my_portfolio.html.erb
<h1>myPortfolio</h1>

<h3>search for stocks</h3>
<div id="stock-lookup">
  <%= form_tag search_stocks_path, method: :get, id: "stock-lookup-form" do %>
<div class="form-group row no-padding text-center col-md-12">
  <div class="col-md-10">
    <%= text_field_tag :stock, params[:stock], placeholder: "stock ticker symbol", autofocus: true, class: "form-control search-box input-lg" %>
    <!-- parmas hash url test -my_portfolio?stock=AAAP -->
  </div>
<div class="col-md-2">
  <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
    <i class="fa fa-search"></i> Look up a stock
  <% end %>
</div>

</div>

  <% end %>
</div>


<div class="well">
<%= @stock.inspect %>
<% if @stock != nil %>
    <%= @stock.name %>
<% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Farts/p>


<%= link_to "logout", destroy_user_session_path, method: :delete %>